[package]
name = "stremio-core-protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]

# Protobuf 
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
prost-build.workspace = true
protox.workspace = true
glob.workspace = true