name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build code
        run: cargo build
      - name: Lint code format
        run: cargo fmt --all -- --check
      - name: Lint code
        run: cargo clippy --all -- -D warnings

      # MSRV
      - name: Check MSRV
        uses: dtolnay/rust-toolchain@1.66.1
      - name: Cargo check
        run: cargo check
