name: Build

on:
  push:
    branches:
      - '**'

# Stops the running workflow of previous pushes
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: stable
  NODE_VERSION: 12

jobs:
  lint:
    name: Lint with rustfmt & clippy (nightly)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Set default Rust toolchain - nightly
      run: rustup default nightly

    - name: Install rustfmt
      run: rustup +nightly component add rustfmt

    - name: Install clippy
      run: rustup +nightly component add clippy

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build crate
      run: cargo build

    - name: Lint - rustfmt
      run: cargo +nightly fmt --all -- --check

    - name: Lint - clippy
      run: cargo +nightly clippy --all --no-deps -- -D warnings

  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Set default Rust version - ${{ env.RUST_VERSION }}
      run: rustup default ${{ env.RUST_VERSION }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test
      run: cargo test

    # This makes sure that `core-kotlin` will be correctly build in release
    # This will prevent issues caused by `debug_assertions` cfg. attributes
    - name: Build in --release
      run: cargo build --release
