name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default rust toolchain
        run: rustup default 1.67.1
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Install clippy
        run: rustup component add clippy
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Lint code format
        run: cargo fmt --all -- --check
      - name: Build code
        run: cargo build
      - name: Lint code
        run: cargo clippy --all -- -D warnings
