name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # add protoc because of stremio-core-csharp
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Rust setup (1.67.1)
        uses: dtolnay/rust-toolchain@1.67.1
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build code
        run: cargo build

      - name: Lint code format
        run: cargo fmt --all -- --check

      - name: Lint code
        run: cargo clippy --all -- -D warnings
